import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Terms of Service — Clipflow',
  description: 'Terms and conditions for using the Clipflow platform.',
}

export default function TermsPage() {
  const updated = 'April 13, 2026'

  return (
    <article className="mx-auto max-w-3xl px-6 py-20">
      <p className="lv2L-eyebrow">Policy · Terms</p>
      <h1>Terms of service.</h1>
      <p className="mt-3 text-[13px]" style={{ color: '#7c7468' }}>Last updated · {updated}</p>

      <h2>1. Acceptance</h2>
      <p>By using Clipflow, you agree to these Terms of Service. If you do not agree, do not use the platform.</p>

      <h2>2. Description of Service</h2>
      <p>Clipflow is an AI-powered content repurposing platform that generates platform-specific drafts from your content. The service includes AI generation, video processing, social scheduling, and related tools.</p>

      <h2>3. BYOK Model</h2>
      <p>Clipflow operates on a Bring Your Own Key (BYOK) model. You are responsible for maintaining valid API keys with your chosen AI provider (OpenAI, Anthropic, Google). Usage of those APIs is subject to each provider&apos;s terms of service and usage policies.</p>

      <h2>4. Your Content</h2>
      <p>You retain full ownership of all content you upload to or create within Clipflow. We do not claim any intellectual property rights over your content. You grant us a limited license to process your content solely for the purpose of providing the service.</p>

      <h2>5. Acceptable Use</h2>
      <p>You agree not to:</p>
      <ul>
        <li>Use the platform to generate illegal, harmful, or misleading content.</li>
        <li>Attempt to circumvent usage limits or billing.</li>
        <li>Reverse engineer or scrape the platform.</li>
        <li>Share your account with unauthorized users.</li>
        <li>Use the platform in violation of your AI provider&apos;s terms.</li>
      </ul>

      <h2>6. Subscriptions & Billing</h2>
      <p>Paid plans are billed monthly via Stripe. You can cancel at any time — access continues until the end of your billing period. Refunds are handled on a case-by-case basis. The free plan is available indefinitely with usage limits.</p>

      <h2>7. Availability</h2>
      <p>We strive for high availability but do not guarantee uninterrupted access. Third-party service outages (AI providers, video rendering, social platforms) may temporarily affect functionality.</p>

      <h2>8. Limitation of Liability</h2>
      <p>Clipflow is provided &ldquo;as is.&rdquo; We are not liable for any indirect, incidental, or consequential damages arising from your use of the platform, including but not limited to lost revenue, data loss, or AI-generated content accuracy.</p>

      <h2>9. AI-Generated Content</h2>
      <p>Content generated by AI through Clipflow may not always be accurate, appropriate, or factually correct. You are responsible for reviewing and editing all AI-generated content before publishing. Clipflow is not responsible for the consequences of publishing AI-generated content.</p>

      <h2>10. Termination</h2>
      <p>We may suspend or terminate accounts that violate these terms. You may delete your account at any time via Settings. Upon termination, your data will be deleted within 30 days.</p>

      <h2>11. Changes</h2>
      <p>We may update these terms. Continued use after changes constitutes acceptance.</p>

      <h2>12. Contact</h2>
      <p>Questions? Email us at <a href="mailto:legal@clipflow.to">legal@clipflow.to</a>.</p>
    </article>
  )
}
