/**
 * Export helpers for generating downloadable content from outputs.
 * These produce plain text/HTML that can be downloaded by the client.
 * For real DOCX generation, we'd need a library like docx or officegen.
 * For MVP, we export as formatted HTML (which can be opened in Word/Docs).
 */

export interface ExportableOutput {
  platform: string
  hook: string
  script: string
  caption: string
  hashtags: string[]
}

/**
 * Exports outputs as a formatted HTML document (can be opened in Word/Google Docs).
 */
export function exportAsHtml(params: {
  contentTitle: string
  outputs: ExportableOutput[]
  includeMetadata?: boolean
}): string {
  const { contentTitle, outputs } = params

  const sections = outputs.map((o) => `
    <div style="page-break-inside:avoid;margin-bottom:32px;padding:20px;border:1px solid #e5e7eb;border-radius:8px;">
      <h2 style="color:#7c3aed;margin:0 0 8px;">${escapeHtml(platformLabel(o.platform))}</h2>
      <h3 style="margin:0 0 4px;font-size:14px;color:#666;">Hook</h3>
      <p style="margin:0 0 16px;font-size:16px;font-weight:600;">${escapeHtml(o.hook)}</p>
      ${o.script ? `<h3 style="margin:0 0 4px;font-size:14px;color:#666;">Script</h3><p style="margin:0 0 16px;white-space:pre-wrap;">${escapeHtml(o.script)}</p>` : ''}
      <h3 style="margin:0 0 4px;font-size:14px;color:#666;">Caption</h3>
      <p style="margin:0 0 16px;">${escapeHtml(o.caption)}</p>
      ${o.hashtags.length > 0 ? `<p style="color:#7c3aed;font-size:14px;">${o.hashtags.map((h) => `#${h}`).join(' ')}</p>` : ''}
    </div>
  `).join('')

  return `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>${escapeHtml(contentTitle)} — Clipflow Export</title>
  <style>body{font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,sans-serif;max-width:800px;margin:0 auto;padding:40px;color:#111;}</style>
</head>
<body>
  <h1 style="font-size:24px;margin-bottom:4px;">${escapeHtml(contentTitle)}</h1>
  <p style="color:#666;margin-top:0;margin-bottom:32px;">Exported from Clipflow · ${new Date().toLocaleDateString()}</p>
  ${sections}
  <p style="margin-top:40px;font-size:12px;color:#999;text-align:center;">Generated by <a href="https://clipflow.to" style="color:#7c3aed;">Clipflow</a></p>
</body>
</html>`
}

/**
 * Exports outputs as plain text (for Markdown/text editors).
 */
export function exportAsText(params: {
  contentTitle: string
  outputs: ExportableOutput[]
}): string {
  const lines = [`# ${params.contentTitle}`, `Exported from Clipflow · ${new Date().toLocaleDateString()}`, '']

  for (const o of params.outputs) {
    lines.push(`## ${platformLabel(o.platform)}`)
    lines.push('')
    lines.push(`**Hook:** ${o.hook}`)
    if (o.script) {
      lines.push('')
      lines.push(`**Script:**`)
      lines.push(o.script)
    }
    lines.push('')
    lines.push(`**Caption:** ${o.caption}`)
    if (o.hashtags.length > 0) {
      lines.push('')
      lines.push(`**Hashtags:** ${o.hashtags.map((h) => `#${h}`).join(' ')}`)
    }
    lines.push('')
    lines.push('---')
    lines.push('')
  }

  return lines.join('\n')
}

/**
 * Exports outputs as CSV.
 */
export function exportAsCsv(params: {
  outputs: ExportableOutput[]
}): string {
  const header = 'Platform,Hook,Script,Caption,Hashtags'
  const rows = params.outputs.map((o) =>
    [o.platform, o.hook, o.script, o.caption, o.hashtags.join(' ')]
      .map((v) => `"${v.replace(/"/g, '""')}"`)
      .join(','),
  )
  return [header, ...rows].join('\n')
}

function platformLabel(p: string): string {
  const labels: Record<string, string> = { tiktok: 'TikTok', instagram_reels: 'Instagram Reels', youtube_shorts: 'YouTube Shorts', linkedin: 'LinkedIn' }
  return labels[p] ?? p
}

function escapeHtml(str: string): string {
  return str.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
}
