'use client'

import { useState } from 'react'
import {
  ArrowDownToLine,
  CheckCircle2,
  FileText,
  Film,
  MessageSquare,
  Scissors,
  Copy,
} from 'lucide-react'

/**
 * Editor Export Panel — lets users download their content in formats
 * compatible with CapCut, Premiere Pro, DaVinci Resolve, Final Cut Pro,
 * or any NLE that supports SRT/VTT/TXT/EDL.
 *
 * Sits on the Content Detail page and optionally the Outputs page.
 */

interface EditorExportPanelProps {
  contentId: string
  contentTitle: string
  /** Plain transcript text. */
  transcript: string
  /** Pre-generated SRT string, if subtitles were already created. */
  srt: string | null
  /** Pre-generated VTT string. */
  vtt: string | null
  /** Best clips with position info for marker export. */
  clips: Array<{
    quote: string
    reason: string
    position_pct: number
    type: string
    estimated_duration: string
  }> | null
  /** Estimated content duration in seconds (for clip timestamp calc). */
  estimatedDurationSec: number | null
}

function downloadFile(content: string, filename: string, mimeType = 'text/plain'): void {
  const blob = new Blob([content], { type: mimeType })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = filename
  a.click()
  URL.revokeObjectURL(url)
}

function formatTimecode(seconds: number): string {
  const h = Math.floor(seconds / 3600)
  const m = Math.floor((seconds % 3600) / 60)
  const s = Math.floor(seconds % 60)
  const f = Math.round((seconds % 1) * 30) // 30fps frame count
  return `${String(h).padStart(2, '0')}:${String(m).padStart(2, '0')}:${String(s).padStart(2, '0')}:${String(f).padStart(2, '0')}`
}

/**
 * Generate a simple EDL (Edit Decision List) from clip markers.
 * CMX 3600 format — importable by Premiere, DaVinci, Final Cut.
 */
function generateEdl(
  clips: NonNullable<EditorExportPanelProps['clips']>,
  duration: number,
  title: string,
): string {
  const lines: string[] = [
    'TITLE: ' + title.replace(/[^a-zA-Z0-9 _-]/g, ''),
    'FCM: NON-DROP FRAME',
    '',
  ]

  clips.forEach((clip, i) => {
    const startSec = (clip.position_pct / 100) * duration
    // Parse estimated_duration like "15-30 seconds" → take midpoint
    const durMatch = clip.estimated_duration.match(/(\d+)-?(\d+)?/)
    const durSec = durMatch
      ? durMatch[2]
        ? (parseInt(durMatch[1]!) + parseInt(durMatch[2]!)) / 2
        : parseInt(durMatch[1]!)
      : 20
    const endSec = Math.min(startSec + durSec, duration)

    const editNum = String(i + 1).padStart(3, '0')
    const srcIn = formatTimecode(startSec)
    const srcOut = formatTimecode(endSec)
    // Record in/out matches source for a simple cut list
    lines.push(`${editNum}  001      V     C        ${srcIn} ${srcOut} ${srcIn} ${srcOut}`)
    lines.push(`* FROM CLIP: ${clip.type.toUpperCase()} — ${clip.quote.slice(0, 60)}`)
    lines.push(`* COMMENT: ${clip.reason.slice(0, 80)}`)
    lines.push('')
  })

  return lines.join('\n')
}

/**
 * Generate a VTT chapters file from clips (usable as YouTube chapters or markers).
 */
function generateChaptersVtt(
  clips: NonNullable<EditorExportPanelProps['clips']>,
  duration: number,
): string {
  const lines: string[] = ['WEBVTT', '', 'NOTE Generated by Clipflow', '']

  clips.forEach((clip, i) => {
    const startSec = (clip.position_pct / 100) * duration
    const durMatch = clip.estimated_duration.match(/(\d+)-?(\d+)?/)
    const durSec = durMatch
      ? durMatch[2]
        ? (parseInt(durMatch[1]!) + parseInt(durMatch[2]!)) / 2
        : parseInt(durMatch[1]!)
      : 20
    const endSec = Math.min(startSec + durSec, duration)

    const fmtStart = formatVttTime(startSec)
    const fmtEnd = formatVttTime(endSec)

    lines.push(`${i + 1}`)
    lines.push(`${fmtStart} --> ${fmtEnd}`)
    lines.push(`[${clip.type}] ${clip.quote}`)
    lines.push('')
  })

  return lines.join('\n')
}

function formatVttTime(seconds: number): string {
  const h = Math.floor(seconds / 3600)
  const m = Math.floor((seconds % 3600) / 60)
  const s = Math.floor(seconds % 60)
  const ms = Math.round((seconds % 1) * 1000)
  return `${String(h).padStart(2, '0')}:${String(m).padStart(2, '0')}:${String(s).padStart(2, '0')}.${String(ms).padStart(3, '0')}`
}

interface ExportOption {
  key: string
  label: string
  desc: string
  icon: React.ComponentType<{ className?: string }>
  format: string
  available: boolean
  onDownload: () => void
}

export function EditorExportPanel({
  contentId: _contentId,
  contentTitle,
  transcript,
  srt,
  vtt,
  clips,
  estimatedDurationSec,
}: EditorExportPanelProps) {
  const [copied, setCopied] = useState(false)
  const safeName = contentTitle.replace(/[^a-zA-Z0-9_-]/g, '_').slice(0, 40)
  const duration = estimatedDurationSec ?? 300

  const handleCopyTranscript = () => {
    navigator.clipboard.writeText(transcript)
    setCopied(true)
    setTimeout(() => setCopied(false), 2000)
  }

  const exports: ExportOption[] = [
    {
      key: 'srt',
      label: 'SRT Subtitles',
      desc: 'CapCut, Premiere, DaVinci, Final Cut',
      icon: MessageSquare,
      format: '.srt',
      available: !!srt,
      onDownload: () => srt && downloadFile(srt, `${safeName}.srt`),
    },
    {
      key: 'vtt',
      label: 'VTT Subtitles',
      desc: 'Web, YouTube, CapCut',
      icon: MessageSquare,
      format: '.vtt',
      available: !!vtt,
      onDownload: () => vtt && downloadFile(vtt, `${safeName}.vtt`, 'text/vtt'),
    },
    {
      key: 'transcript',
      label: 'Plain Transcript',
      desc: 'Text file for any editor or teleprompter',
      icon: FileText,
      format: '.txt',
      available: transcript.length > 0,
      onDownload: () =>
        downloadFile(
          `${contentTitle}\n${'='.repeat(contentTitle.length)}\n\nTranscript exported from Clipflow\n\n${transcript}`,
          `${safeName}_transcript.txt`,
        ),
    },
    {
      key: 'edl',
      label: 'EDL Clip Markers',
      desc: 'Premiere, DaVinci, Avid — import as timeline markers',
      icon: Scissors,
      format: '.edl',
      available: !!clips && clips.length > 0,
      onDownload: () =>
        clips &&
        downloadFile(
          generateEdl(clips, duration, contentTitle),
          `${safeName}_clips.edl`,
        ),
    },
    {
      key: 'chapters-vtt',
      label: 'Chapter Markers',
      desc: 'VTT chapters for YouTube or clip navigation',
      icon: Film,
      format: '.vtt',
      available: !!clips && clips.length > 0,
      onDownload: () =>
        clips &&
        downloadFile(
          generateChaptersVtt(clips, duration),
          `${safeName}_chapters.vtt`,
          'text/vtt',
        ),
    },
  ]

  const availableExports = exports.filter((e) => e.available)
  const unavailableExports = exports.filter((e) => !e.available)

  return (
    <div className="rounded-2xl border border-border/50 bg-card">
      <div className="flex items-center justify-between border-b border-border/40 px-5 py-3">
        <div className="flex items-center gap-2.5">
          <div className="flex h-7 w-7 items-center justify-center rounded-lg bg-pink-50 text-pink-600">
            <ArrowDownToLine className="h-3.5 w-3.5" />
          </div>
          <div>
            <p className="text-sm font-bold">Export for editors</p>
            <p className="text-[10px] text-muted-foreground">
              CapCut · Premiere · DaVinci · Final Cut
            </p>
          </div>
        </div>
        <button
          onClick={handleCopyTranscript}
          className="flex items-center gap-1.5 rounded-lg border border-border/50 px-3 py-1.5 text-[11px] font-semibold text-muted-foreground transition-all hover:border-primary/30 hover:text-primary"
        >
          {copied ? (
            <>
              <CheckCircle2 className="h-3 w-3 text-emerald-500" />
              Copied
            </>
          ) : (
            <>
              <Copy className="h-3 w-3" />
              Copy transcript
            </>
          )}
        </button>
      </div>

      <div className="grid gap-2 p-4 sm:grid-cols-2 lg:grid-cols-3">
        {availableExports.map((exp) => {
          const Icon = exp.icon
          return (
            <button
              key={exp.key}
              onClick={exp.onDownload}
              className="group flex items-start gap-3 rounded-xl border border-border/40 bg-background p-3.5 text-left transition-all hover:-translate-y-0.5 hover:border-primary/25 hover:shadow-md hover:shadow-primary/[0.05]"
            >
              <div className="flex h-9 w-9 shrink-0 items-center justify-center rounded-xl bg-primary/10 text-primary transition-colors group-hover:bg-primary/15">
                <Icon className="h-4 w-4" />
              </div>
              <div className="min-w-0 flex-1">
                <div className="flex items-center gap-2">
                  <p className="text-xs font-bold">{exp.label}</p>
                  <span className="rounded bg-muted px-1.5 py-0.5 font-mono text-[9px] text-muted-foreground">
                    {exp.format}
                  </span>
                </div>
                <p className="mt-0.5 text-[10px] leading-relaxed text-muted-foreground">
                  {exp.desc}
                </p>
              </div>
              <ArrowDownToLine className="h-3.5 w-3.5 shrink-0 text-muted-foreground/30 transition-all group-hover:text-primary" />
            </button>
          )
        })}

        {unavailableExports.map((exp) => {
          const Icon = exp.icon
          return (
            <div
              key={exp.key}
              className="flex items-start gap-3 rounded-xl border border-dashed border-border/30 bg-muted/10 p-3.5 opacity-50"
            >
              <div className="flex h-9 w-9 shrink-0 items-center justify-center rounded-xl bg-muted text-muted-foreground">
                <Icon className="h-4 w-4" />
              </div>
              <div className="min-w-0 flex-1">
                <div className="flex items-center gap-2">
                  <p className="text-xs font-bold text-muted-foreground">{exp.label}</p>
                  <span className="rounded bg-muted px-1.5 py-0.5 font-mono text-[9px] text-muted-foreground">
                    {exp.format}
                  </span>
                </div>
                <p className="mt-0.5 text-[10px] leading-relaxed text-muted-foreground">
                  {exp.key === 'srt' || exp.key === 'vtt'
                    ? 'Generate subtitles first'
                    : exp.key === 'edl' || exp.key === 'chapters-vtt'
                      ? 'Run Clip Finder first'
                      : 'Not available'}
                </p>
              </div>
            </div>
          )
        })}
      </div>
    </div>
  )
}
