// ---------------------------------------------------------------------------
// Manually authored Database type stub.
//
// In normal operation this file is regenerated from the local Supabase DB via:
//   pnpm db:types
//
// The hand-written types below are kept in sync with
// supabase/migrations/20260411000000_init.sql and 20260412000000_onboarding.sql
// so that the generic parameter on `createServerClient<Database>()` gives us
// real field-level type safety even before `pnpm db:types` has run.
//
// NOTE: Update types are spelled out explicitly (not derived via
// `Partial<Insert>`) because the self-referential lookup
// `Partial<Database['public']['Tables']['x']['Insert']>` causes TypeScript's
// Supabase-js query builder inference to collapse to `never`.
// ---------------------------------------------------------------------------

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[]

export type WorkspaceType = 'personal' | 'team' | 'client'
export type WorkspaceRole = 'owner' | 'editor' | 'viewer' | 'client'
export type ContentKind = 'video' | 'text' | 'youtube' | 'url' | 'rss'
export type ContentStatus = 'uploading' | 'processing' | 'ready' | 'failed'
export type OutputPlatform =
  | 'tiktok'
  | 'instagram_reels'
  | 'youtube_shorts'
  | 'linkedin'
  | 'pinterest'
export type OutputState = 'draft' | 'review' | 'approved' | 'exported'
export type OnboardingRoleType = 'solo' | 'team' | 'agency'
export type AiProvider =
  | 'openai'
  | 'anthropic'
  | 'google'
  | 'shotstack'
  | 'replicate'
  | 'elevenlabs'
  | 'upload-post'
export type BillingPlan = 'free' | 'solo' | 'team' | 'agency'
export type ReferralStatus = 'pending' | 'confirmed' | 'blocked'
export type ScraperFeature =
  | 'trending_sounds'
  | 'hashtag_query'
  | 'competitor_analysis'
  | 'viral_discovery'
  | 'comment_mining'
export type RenderKind =
  | 'burn_captions'
  | 'assemble_broll'
  | 'branded_video'
  | 'clip'
  | 'batch_clip'
  | 'reframe'
  | 'subtitles'
  | 'avatar'
  | 'dub'
  | 'faceless'
export type RenderStatus = 'rendering' | 'done' | 'failed'
export type RenderProvider = 'shotstack' | 'replicate'
export type RenderPriority = 'normal' | 'high'
export type HighlightStatus = 'draft' | 'rendering' | 'ready' | 'failed'
export type FeedbackType = 'bug' | 'feature' | 'feedback'
export type SubscriptionStatus =
  | 'trialing'
  | 'active'
  | 'past_due'
  | 'canceled'
  | 'unpaid'
  | 'incomplete'
  | 'incomplete_expired'
  | 'paused'


// Database type below auto-generated by 'supabase gen types typescript --linked'.
// Re-run after every migration. Top-level aliases above are hand-maintained.

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: "14.5"
  }
  graphql_public: {
    Tables: {
      [_ in never]: never
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      graphql: {
        Args: {
          extensions?: Json
          operationName?: string
          query?: string
          variables?: Json
        }
        Returns: Json
      }
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
  public: {
    Tables: {
      ai_keys: {
        Row: {
          auth_tag: string
          ciphertext: string
          created_at: string
          created_by: string
          id: string
          iv: string
          label: string | null
          masked_preview: string | null
          provider: string
          workspace_id: string
        }
        Insert: {
          auth_tag: string
          ciphertext: string
          created_at?: string
          created_by: string
          id?: string
          iv: string
          label?: string | null
          masked_preview?: string | null
          provider: string
          workspace_id: string
        }
        Update: {
          auth_tag?: string
          ciphertext?: string
          created_at?: string
          created_by?: string
          id?: string
          iv?: string
          label?: string | null
          masked_preview?: string | null
          provider?: string
          workspace_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "ai_keys_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "ai_keys_workspace_id_fkey"
            columns: ["workspace_id"]
            isOneToOne: false
            referencedRelation: "workspaces"
            referencedColumns: ["id"]
          },
        ]
      }
      ai_personas: {
        Row: {
          backstory: string
          created_at: string
          example_responses: string
          expertise_areas: string[]
          id: string
          is_active: boolean
          name: string
          updated_at: string
          workspace_id: string
          writing_quirks: string
        }
        Insert: {
          backstory?: string
          created_at?: string
          example_responses?: string
          expertise_areas?: string[]
          id?: string
          is_active?: boolean
          name: string
          updated_at?: string
          workspace_id: string
          writing_quirks?: string
        }
        Update: {
          backstory?: string
          created_at?: string
          example_responses?: string
          expertise_areas?: string[]
          id?: string
          is_active?: boolean
          name?: string
          updated_at?: string
          workspace_id?: string
          writing_quirks?: string
        }
        Relationships: [
          {
            foreignKeyName: "ai_personas_workspace_id_fkey"
            columns: ["workspace_id"]
            isOneToOne: false
            referencedRelation: "workspaces"
            referencedColumns: ["id"]
          },
        ]
      }
      algorithm_updates: {
        Row: {
          ai_recommendations: string[]
          fetched_at: string
          id: string
          platforms: string[]
          published_at: string | null
          source: string
          summary: string | null
          title: string
          url: string | null
        }
        Insert: {
          ai_recommendations?: string[]
          fetched_at?: string
          id?: string
          platforms?: string[]
          published_at?: string | null
          source: string
          summary?: string | null
          title: string
          url?: string | null
        }
        Update: {
          ai_recommendations?: string[]
          fetched_at?: string
          id?: string
          platforms?: string[]
          published_at?: string | null
          source?: string
          summary?: string | null
          title?: string
          url?: string | null
        }
        Relationships: []
      }
      audit_log: {
        Row: {
          action: string
          actor_email: string | null
          actor_id: string | null
          created_at: string
          id: string
          ip: string | null
          metadata: Json
          target_id: string | null
          target_type: string | null
          user_agent: string | null
          workspace_id: string
        }
        Insert: {
          action: string
          actor_email?: string | null
          actor_id?: string | null
          created_at?: string
          id?: string
          ip?: string | null
          metadata?: Json
          target_id?: string | null
          target_type?: string | null
          user_agent?: string | null
          workspace_id: string
        }
        Update: {
          action?: string
          actor_email?: string | null
          actor_id?: string | null
          created_at?: string
          id?: string
          ip?: string | null
          metadata?: Json
          target_id?: string | null
          target_type?: string | null
          user_agent?: string | null
          workspace_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "audit_log_workspace_id_fkey"
            columns: ["workspace_id"]
            isOneToOne: false
            referencedRelation: "workspaces"
            referencedColumns: ["id"]
          },
        ]
      }
      brand_voices: {
        Row: {
          avoid: string | null
          created_at: string
          example_hook: string | null
          id: string
          is_active: boolean
          name: string
          tone: string | null
          updated_at: string
          workspace_id: string
        }
        Insert: {
          avoid?: string | null
          created_at?: string
          example_hook?: string | null
          id?: string
          is_active?: boolean
          name: string
          tone?: string | null
          updated_at?: string
          workspace_id: string
        }
        Update: {
          avoid?: string | null
          created_at?: string
          example_hook?: string | null
          id?: string
          is_active?: boolean
          name?: string
          tone?: string | null
          updated_at?: string
          workspace_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "brand_voices_workspace_id_fkey"
            columns: ["workspace_id"]
            isOneToOne: false
            referencedRelation: "workspaces"
            referencedColumns: ["id"]
          },
        ]
      }
      content_highlights: {
        Row: {
          aspect_ratio: string
          caption_style: string
          content_id: string
          created_at: string
          created_by: string | null
          crop_x: number | null
          end_seconds: number
          hook_text: string | null
          id: string
          is_user_edited: boolean
          metadata: Json
          reason: string | null
          render_error: string | null
          render_id: string | null
          selected_for_drafts: boolean
          start_seconds: number
          status: Database["public"]["Enums"]["highlight_status"]
          thumbnail_url: string | null
          updated_at: string
          video_url: string | null
          virality_score: number | null
          workspace_id: string
        }
        Insert: {
          aspect_ratio?: string
          caption_style?: string
          content_id: string
          created_at?: string
          created_by?: string | null
          crop_x?: number | null
          end_seconds: number
          hook_text?: string | null
          id?: string
          is_user_edited?: boolean
          metadata?: Json
          reason?: string | null
          render_error?: string | null
          render_id?: string | null
          selected_for_drafts?: boolean
          start_seconds: number
          status?: Database["public"]["Enums"]["highlight_status"]
          thumbnail_url?: string | null
          updated_at?: string
          video_url?: string | null
          virality_score?: number | null
          workspace_id: string
        }
        Update: {
          aspect_ratio?: string
          caption_style?: string
          content_id?: string
          created_at?: string
          created_by?: string | null
          crop_x?: number | null
          end_seconds?: number
          hook_text?: string | null
          id?: string
          is_user_edited?: boolean
          metadata?: Json
          reason?: string | null
          render_error?: string | null
          render_id?: string | null
          selected_for_drafts?: boolean
          start_seconds?: number
          status?: Database["public"]["Enums"]["highlight_status"]
          thumbnail_url?: string | null
          updated_at?: string
          video_url?: string | null
          virality_score?: number | null
          workspace_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "content_highlights_content_id_fkey"
            columns: ["content_id"]
            isOneToOne: false
            referencedRelation: "content_items"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "content_highlights_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "content_highlights_workspace_id_fkey"
            columns: ["workspace_id"]
            isOneToOne: false
            referencedRelation: "workspaces"
            referencedColumns: ["id"]
          },
        ]
      }
      content_items: {
        Row: {
          created_at: string
          created_by: string
          deleted_at: string | null
          id: string
          kind: Database["public"]["Enums"]["content_kind"]
          metadata: Json
          processing_phase: string | null
          processing_progress: number | null
          project_id: string | null
          source_url: string | null
          status: Database["public"]["Enums"]["content_status"]
          title: string | null
          transcript: string | null
          transcript_words: Json | null
          updated_at: string
          workspace_id: string
        }
        Insert: {
          created_at?: string
          created_by: string
          deleted_at?: string | null
          id?: string
          kind: Database["public"]["Enums"]["content_kind"]
          metadata?: Json
          processing_phase?: string | null
          processing_progress?: number | null
          project_id?: string | null
          source_url?: string | null
          status?: Database["public"]["Enums"]["content_status"]
          title?: string | null
          transcript?: string | null
          transcript_words?: Json | null
          updated_at?: string
          workspace_id: string
        }
        Update: {
          created_at?: string
          created_by?: string
          deleted_at?: string | null
          id?: string
          kind?: Database["public"]["Enums"]["content_kind"]
          metadata?: Json
          processing_phase?: string | null
          processing_progress?: number | null
          project_id?: string | null
          source_url?: string | null
          status?: Database["public"]["Enums"]["content_status"]
          title?: string | null
          transcript?: string | null
          transcript_words?: Json | null
          updated_at?: string
          workspace_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "content_items_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "content_items_project_id_fkey"
            columns: ["project_id"]
            isOneToOne: false
            referencedRelation: "projects"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "content_items_workspace_id_fkey"
            columns: ["workspace_id"]
            isOneToOne: false
            referencedRelation: "workspaces"
            referencedColumns: ["id"]
          },
        ]
      }
      email_deliveries: {
        Row: {
          id: string
          kind: string
          metadata: Json | null
          sent_at: string
          user_id: string
        }
        Insert: {
          id?: string
          kind: string
          metadata?: Json | null
          sent_at?: string
          user_id: string
        }
        Update: {
          id?: string
          kind?: string
          metadata?: Json | null
          sent_at?: string
          user_id?: string
        }
        Relationships: []
      }
      mfa_recovery_codes: {
        Row: {
          code_hash: string
          created_at: string
          id: string
          used_at: string | null
          user_id: string
        }
        Insert: {
          code_hash: string
          created_at?: string
          id?: string
          used_at?: string | null
          user_id: string
        }
        Update: {
          code_hash?: string
          created_at?: string
          id?: string
          used_at?: string | null
          user_id?: string
        }
        Relationships: []
      }
      notifications: {
        Row: {
          body: string | null
          created_at: string
          id: string
          link: string | null
          read: boolean
          title: string
          type: string
          user_id: string
          workspace_id: string | null
        }
        Insert: {
          body?: string | null
          created_at?: string
          id?: string
          link?: string | null
          read?: boolean
          title: string
          type: string
          user_id: string
          workspace_id?: string | null
        }
        Update: {
          body?: string | null
          created_at?: string
          id?: string
          link?: string | null
          read?: boolean
          title?: string
          type?: string
          user_id?: string
          workspace_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "notifications_workspace_id_fkey"
            columns: ["workspace_id"]
            isOneToOne: false
            referencedRelation: "workspaces"
            referencedColumns: ["id"]
          },
        ]
      }
      output_states: {
        Row: {
          changed_by: string | null
          created_at: string
          id: string
          note: string | null
          output_id: string
          state: Database["public"]["Enums"]["output_state"]
          workspace_id: string
        }
        Insert: {
          changed_by?: string | null
          created_at?: string
          id?: string
          note?: string | null
          output_id: string
          state: Database["public"]["Enums"]["output_state"]
          workspace_id: string
        }
        Update: {
          changed_by?: string | null
          created_at?: string
          id?: string
          note?: string | null
          output_id?: string
          state?: Database["public"]["Enums"]["output_state"]
          workspace_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "output_states_changed_by_fkey"
            columns: ["changed_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "output_states_output_id_fkey"
            columns: ["output_id"]
            isOneToOne: false
            referencedRelation: "outputs"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "output_states_workspace_id_fkey"
            columns: ["workspace_id"]
            isOneToOne: false
            referencedRelation: "workspaces"
            referencedColumns: ["id"]
          },
        ]
      }
      output_templates: {
        Row: {
          created_at: string
          created_by: string | null
          id: string
          is_default: boolean
          name: string
          platform: string
          structure_hint: string | null
          system_prompt: string
          workspace_id: string
        }
        Insert: {
          created_at?: string
          created_by?: string | null
          id?: string
          is_default?: boolean
          name: string
          platform: string
          structure_hint?: string | null
          system_prompt: string
          workspace_id: string
        }
        Update: {
          created_at?: string
          created_by?: string | null
          id?: string
          is_default?: boolean
          name?: string
          platform?: string
          structure_hint?: string | null
          system_prompt?: string
          workspace_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "output_templates_workspace_id_fkey"
            columns: ["workspace_id"]
            isOneToOne: false
            referencedRelation: "workspaces"
            referencedColumns: ["id"]
          },
        ]
      }
      output_versions: {
        Row: {
          body: string
          created_at: string
          created_by: string | null
          id: string
          metadata: Json
          output_id: string
          source: string
          version_number: number
          workspace_id: string
        }
        Insert: {
          body: string
          created_at?: string
          created_by?: string | null
          id?: string
          metadata?: Json
          output_id: string
          source: string
          version_number: number
          workspace_id: string
        }
        Update: {
          body?: string
          created_at?: string
          created_by?: string | null
          id?: string
          metadata?: Json
          output_id?: string
          source?: string
          version_number?: number
          workspace_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "output_versions_output_id_fkey"
            columns: ["output_id"]
            isOneToOne: false
            referencedRelation: "outputs"
            referencedColumns: ["id"]
          },
        ]
      }
      outputs: {
        Row: {
          body: string | null
          content_id: string
          created_at: string
          current_state: string
          deleted_at: string | null
          id: string
          is_starred: boolean
          metadata: Json
          platform: Database["public"]["Enums"]["output_platform"]
          scheduled_for: string | null
          updated_at: string
          workspace_id: string
        }
        Insert: {
          body?: string | null
          content_id: string
          created_at?: string
          current_state?: string
          deleted_at?: string | null
          id?: string
          is_starred?: boolean
          metadata?: Json
          platform: Database["public"]["Enums"]["output_platform"]
          scheduled_for?: string | null
          updated_at?: string
          workspace_id: string
        }
        Update: {
          body?: string | null
          content_id?: string
          created_at?: string
          current_state?: string
          deleted_at?: string | null
          id?: string
          is_starred?: boolean
          metadata?: Json
          platform?: Database["public"]["Enums"]["output_platform"]
          scheduled_for?: string | null
          updated_at?: string
          workspace_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "outputs_content_id_fkey"
            columns: ["content_id"]
            isOneToOne: false
            referencedRelation: "content_items"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "outputs_workspace_id_fkey"
            columns: ["workspace_id"]
            isOneToOne: false
            referencedRelation: "workspaces"
            referencedColumns: ["id"]
          },
        ]
      }
      processed_stripe_events: {
        Row: {
          event_id: string
          processed_at: string
          type: string
        }
        Insert: {
          event_id: string
          processed_at?: string
          type: string
        }
        Update: {
          event_id?: string
          processed_at?: string
          type?: string
        }
        Relationships: []
      }
      profiles: {
        Row: {
          avatar_url: string | null
          created_at: string
          email: string
          full_name: string | null
          id: string
          onboarded_at: string | null
          referral_code: string
          role_type: string | null
          updated_at: string
        }
        Insert: {
          avatar_url?: string | null
          created_at?: string
          email: string
          full_name?: string | null
          id: string
          onboarded_at?: string | null
          referral_code: string
          role_type?: string | null
          updated_at?: string
        }
        Update: {
          avatar_url?: string | null
          created_at?: string
          email?: string
          full_name?: string | null
          id?: string
          onboarded_at?: string | null
          referral_code?: string
          role_type?: string | null
          updated_at?: string
        }
        Relationships: []
      }
      projects: {
        Row: {
          created_at: string
          created_by: string
          description: string | null
          id: string
          name: string
          updated_at: string
          workspace_id: string
        }
        Insert: {
          created_at?: string
          created_by: string
          description?: string | null
          id?: string
          name: string
          updated_at?: string
          workspace_id: string
        }
        Update: {
          created_at?: string
          created_by?: string
          description?: string | null
          id?: string
          name?: string
          updated_at?: string
          workspace_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "projects_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "projects_workspace_id_fkey"
            columns: ["workspace_id"]
            isOneToOne: false
            referencedRelation: "workspaces"
            referencedColumns: ["id"]
          },
        ]
      }
      referrals: {
        Row: {
          confirmed_at: string | null
          created_at: string
          id: string
          paid_invoice_id: string | null
          referee_user_id: string
          referrer_user_id: string
          reversal_reason: string | null
          reversed_at: string | null
          source: string | null
          status: Database["public"]["Enums"]["referral_status"]
        }
        Insert: {
          confirmed_at?: string | null
          created_at?: string
          id?: string
          paid_invoice_id?: string | null
          referee_user_id: string
          referrer_user_id: string
          reversal_reason?: string | null
          reversed_at?: string | null
          source?: string | null
          status?: Database["public"]["Enums"]["referral_status"]
        }
        Update: {
          confirmed_at?: string | null
          created_at?: string
          id?: string
          paid_invoice_id?: string | null
          referee_user_id?: string
          referrer_user_id?: string
          reversal_reason?: string | null
          reversed_at?: string | null
          source?: string | null
          status?: Database["public"]["Enums"]["referral_status"]
        }
        Relationships: [
          {
            foreignKeyName: "referrals_referee_user_id_fkey"
            columns: ["referee_user_id"]
            isOneToOne: true
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "referrals_referrer_user_id_fkey"
            columns: ["referrer_user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      renders: {
        Row: {
          content_id: string | null
          created_at: string
          created_by: string | null
          error: string | null
          id: string
          kind: Database["public"]["Enums"]["render_kind"]
          metadata: Json
          priority: Database["public"]["Enums"]["render_priority"]
          provider: Database["public"]["Enums"]["render_provider"]
          provider_render_id: string | null
          status: Database["public"]["Enums"]["render_status"]
          updated_at: string
          url: string | null
          workspace_id: string
        }
        Insert: {
          content_id?: string | null
          created_at?: string
          created_by?: string | null
          error?: string | null
          id?: string
          kind: Database["public"]["Enums"]["render_kind"]
          metadata?: Json
          priority?: Database["public"]["Enums"]["render_priority"]
          provider?: Database["public"]["Enums"]["render_provider"]
          provider_render_id?: string | null
          status?: Database["public"]["Enums"]["render_status"]
          updated_at?: string
          url?: string | null
          workspace_id: string
        }
        Update: {
          content_id?: string | null
          created_at?: string
          created_by?: string | null
          error?: string | null
          id?: string
          kind?: Database["public"]["Enums"]["render_kind"]
          metadata?: Json
          priority?: Database["public"]["Enums"]["render_priority"]
          provider?: Database["public"]["Enums"]["render_provider"]
          provider_render_id?: string | null
          status?: Database["public"]["Enums"]["render_status"]
          updated_at?: string
          url?: string | null
          workspace_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "renders_content_id_fkey"
            columns: ["content_id"]
            isOneToOne: false
            referencedRelation: "content_items"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "renders_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "renders_workspace_id_fkey"
            columns: ["workspace_id"]
            isOneToOne: false
            referencedRelation: "workspaces"
            referencedColumns: ["id"]
          },
        ]
      }
      review_comments: {
        Row: {
          body: string
          created_at: string
          id: string
          output_id: string | null
          review_link_id: string
          reviewer_email: string | null
          reviewer_name: string
        }
        Insert: {
          body: string
          created_at?: string
          id?: string
          output_id?: string | null
          review_link_id: string
          reviewer_email?: string | null
          reviewer_name: string
        }
        Update: {
          body?: string
          created_at?: string
          id?: string
          output_id?: string | null
          review_link_id?: string
          reviewer_email?: string | null
          reviewer_name?: string
        }
        Relationships: [
          {
            foreignKeyName: "review_comments_output_id_fkey"
            columns: ["output_id"]
            isOneToOne: false
            referencedRelation: "outputs"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "review_comments_review_link_id_fkey"
            columns: ["review_link_id"]
            isOneToOne: false
            referencedRelation: "review_links"
            referencedColumns: ["id"]
          },
        ]
      }
      review_links: {
        Row: {
          content_id: string
          created_at: string
          created_by: string
          expires_at: string | null
          id: string
          is_active: boolean
          label: string | null
          token: string
          workspace_id: string
        }
        Insert: {
          content_id: string
          created_at?: string
          created_by: string
          expires_at?: string | null
          id?: string
          is_active?: boolean
          label?: string | null
          token?: string
          workspace_id: string
        }
        Update: {
          content_id?: string
          created_at?: string
          created_by?: string
          expires_at?: string | null
          id?: string
          is_active?: boolean
          label?: string | null
          token?: string
          workspace_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "review_links_content_id_fkey"
            columns: ["content_id"]
            isOneToOne: false
            referencedRelation: "content_items"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "review_links_workspace_id_fkey"
            columns: ["workspace_id"]
            isOneToOne: false
            referencedRelation: "workspaces"
            referencedColumns: ["id"]
          },
        ]
      }
      rss_subscriptions: {
        Row: {
          channel_title: string | null
          created_at: string
          created_by: string | null
          feed_url: string
          id: string
          last_error: string | null
          last_polled_at: string | null
          last_seen_guid: string | null
          updated_at: string
          workspace_id: string
        }
        Insert: {
          channel_title?: string | null
          created_at?: string
          created_by?: string | null
          feed_url: string
          id?: string
          last_error?: string | null
          last_polled_at?: string | null
          last_seen_guid?: string | null
          updated_at?: string
          workspace_id: string
        }
        Update: {
          channel_title?: string | null
          created_at?: string
          created_by?: string | null
          feed_url?: string
          id?: string
          last_error?: string | null
          last_polled_at?: string | null
          last_seen_guid?: string | null
          updated_at?: string
          workspace_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "rss_subscriptions_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "rss_subscriptions_workspace_id_fkey"
            columns: ["workspace_id"]
            isOneToOne: false
            referencedRelation: "workspaces"
            referencedColumns: ["id"]
          },
        ]
      }
      scheduled_posts: {
        Row: {
          created_at: string
          created_by: string | null
          error_message: string | null
          id: string
          metadata: Json | null
          next_retry_at: string | null
          output_id: string
          platform: string
          platform_post_id: string | null
          published_at: string | null
          retry_count: number
          scheduled_for: string
          social_account_id: string | null
          stats_fetched_at: string | null
          status: string
          workspace_id: string
        }
        Insert: {
          created_at?: string
          created_by?: string | null
          error_message?: string | null
          id?: string
          metadata?: Json | null
          next_retry_at?: string | null
          output_id: string
          platform: string
          platform_post_id?: string | null
          published_at?: string | null
          retry_count?: number
          scheduled_for: string
          social_account_id?: string | null
          stats_fetched_at?: string | null
          status?: string
          workspace_id: string
        }
        Update: {
          created_at?: string
          created_by?: string | null
          error_message?: string | null
          id?: string
          metadata?: Json | null
          next_retry_at?: string | null
          output_id?: string
          platform?: string
          platform_post_id?: string | null
          published_at?: string | null
          retry_count?: number
          scheduled_for?: string
          social_account_id?: string | null
          stats_fetched_at?: string | null
          status?: string
          workspace_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "scheduled_posts_output_id_fkey"
            columns: ["output_id"]
            isOneToOne: false
            referencedRelation: "outputs"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "scheduled_posts_social_account_id_fkey"
            columns: ["social_account_id"]
            isOneToOne: false
            referencedRelation: "social_accounts"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "scheduled_posts_workspace_id_fkey"
            columns: ["workspace_id"]
            isOneToOne: false
            referencedRelation: "workspaces"
            referencedColumns: ["id"]
          },
        ]
      }
      scraper_cache: {
        Row: {
          actor: string
          cache_key: string
          created_at: string
          data: Json
          expires_at: string
          updated_at: string
        }
        Insert: {
          actor: string
          cache_key: string
          created_at?: string
          data: Json
          expires_at: string
          updated_at?: string
        }
        Update: {
          actor?: string
          cache_key?: string
          created_at?: string
          data?: Json
          expires_at?: string
          updated_at?: string
        }
        Relationships: []
      }
      scraper_usage: {
        Row: {
          cache_hit: boolean
          cache_key: string | null
          created_at: string
          created_by: string | null
          feature: Database["public"]["Enums"]["scraper_feature"]
          id: string
          target: string | null
          workspace_id: string
        }
        Insert: {
          cache_hit?: boolean
          cache_key?: string | null
          created_at?: string
          created_by?: string | null
          feature: Database["public"]["Enums"]["scraper_feature"]
          id?: string
          target?: string | null
          workspace_id: string
        }
        Update: {
          cache_hit?: boolean
          cache_key?: string | null
          created_at?: string
          created_by?: string | null
          feature?: Database["public"]["Enums"]["scraper_feature"]
          id?: string
          target?: string | null
          workspace_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "scraper_usage_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "scraper_usage_workspace_id_fkey"
            columns: ["workspace_id"]
            isOneToOne: false
            referencedRelation: "workspaces"
            referencedColumns: ["id"]
          },
        ]
      }
      social_accounts: {
        Row: {
          access_token_auth_tag: string | null
          access_token_ciphertext: string | null
          access_token_iv: string | null
          created_at: string
          expires_at: string | null
          id: string
          platform: string
          platform_user_id: string
          platform_username: string | null
          refresh_token_auth_tag: string | null
          refresh_token_ciphertext: string | null
          refresh_token_iv: string | null
          user_id: string
          workspace_id: string
        }
        Insert: {
          access_token_auth_tag?: string | null
          access_token_ciphertext?: string | null
          access_token_iv?: string | null
          created_at?: string
          expires_at?: string | null
          id?: string
          platform: string
          platform_user_id: string
          platform_username?: string | null
          refresh_token_auth_tag?: string | null
          refresh_token_ciphertext?: string | null
          refresh_token_iv?: string | null
          user_id: string
          workspace_id: string
        }
        Update: {
          access_token_auth_tag?: string | null
          access_token_ciphertext?: string | null
          access_token_iv?: string | null
          created_at?: string
          expires_at?: string | null
          id?: string
          platform?: string
          platform_user_id?: string
          platform_username?: string | null
          refresh_token_auth_tag?: string | null
          refresh_token_ciphertext?: string | null
          refresh_token_iv?: string | null
          user_id?: string
          workspace_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "social_accounts_workspace_id_fkey"
            columns: ["workspace_id"]
            isOneToOne: false
            referencedRelation: "workspaces"
            referencedColumns: ["id"]
          },
        ]
      }
      subscriptions: {
        Row: {
          cancel_at_period_end: boolean
          created_at: string
          current_period_end: string | null
          id: string
          plan: Database["public"]["Enums"]["billing_plan"]
          status: Database["public"]["Enums"]["subscription_status"] | null
          stripe_customer_id: string | null
          stripe_subscription_id: string | null
          updated_at: string
          workspace_id: string
        }
        Insert: {
          cancel_at_period_end?: boolean
          created_at?: string
          current_period_end?: string | null
          id?: string
          plan?: Database["public"]["Enums"]["billing_plan"]
          status?: Database["public"]["Enums"]["subscription_status"] | null
          stripe_customer_id?: string | null
          stripe_subscription_id?: string | null
          updated_at?: string
          workspace_id: string
        }
        Update: {
          cancel_at_period_end?: boolean
          created_at?: string
          current_period_end?: string | null
          id?: string
          plan?: Database["public"]["Enums"]["billing_plan"]
          status?: Database["public"]["Enums"]["subscription_status"] | null
          stripe_customer_id?: string | null
          stripe_subscription_id?: string | null
          updated_at?: string
          workspace_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "subscriptions_workspace_id_fkey"
            columns: ["workspace_id"]
            isOneToOne: false
            referencedRelation: "workspaces"
            referencedColumns: ["id"]
          },
        ]
      }
      user_feedback: {
        Row: {
          created_at: string
          id: string
          message: string
          metadata: Json
          type: Database["public"]["Enums"]["feedback_type"]
          user_id: string | null
        }
        Insert: {
          created_at?: string
          id?: string
          message: string
          metadata?: Json
          type: Database["public"]["Enums"]["feedback_type"]
          user_id?: string | null
        }
        Update: {
          created_at?: string
          id?: string
          message?: string
          metadata?: Json
          type?: Database["public"]["Enums"]["feedback_type"]
          user_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "user_feedback_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      voice_clones: {
        Row: {
          created_at: string
          created_by: string | null
          elevenlabs_voice_id: string
          id: string
          is_default: boolean
          name: string
          sample_url: string | null
          workspace_id: string
        }
        Insert: {
          created_at?: string
          created_by?: string | null
          elevenlabs_voice_id: string
          id?: string
          is_default?: boolean
          name: string
          sample_url?: string | null
          workspace_id: string
        }
        Update: {
          created_at?: string
          created_by?: string | null
          elevenlabs_voice_id?: string
          id?: string
          is_default?: boolean
          name?: string
          sample_url?: string | null
          workspace_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "voice_clones_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "voice_clones_workspace_id_fkey"
            columns: ["workspace_id"]
            isOneToOne: false
            referencedRelation: "workspaces"
            referencedColumns: ["id"]
          },
        ]
      }
      webhooks: {
        Row: {
          created_at: string
          created_by: string | null
          events: string[]
          id: string
          is_active: boolean
          last_status: number | null
          last_triggered_at: string | null
          name: string
          url: string
          workspace_id: string
        }
        Insert: {
          created_at?: string
          created_by?: string | null
          events?: string[]
          id?: string
          is_active?: boolean
          last_status?: number | null
          last_triggered_at?: string | null
          name: string
          url: string
          workspace_id: string
        }
        Update: {
          created_at?: string
          created_by?: string | null
          events?: string[]
          id?: string
          is_active?: boolean
          last_status?: number | null
          last_triggered_at?: string | null
          name?: string
          url?: string
          workspace_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "webhooks_workspace_id_fkey"
            columns: ["workspace_id"]
            isOneToOne: false
            referencedRelation: "workspaces"
            referencedColumns: ["id"]
          },
        ]
      }
      workspace_invites: {
        Row: {
          created_at: string
          email: string | null
          expires_at: string
          id: string
          invited_by: string
          is_accepted: boolean
          role: Database["public"]["Enums"]["workspace_role"]
          token: string
          workspace_id: string
        }
        Insert: {
          created_at?: string
          email?: string | null
          expires_at?: string
          id?: string
          invited_by: string
          is_accepted?: boolean
          role?: Database["public"]["Enums"]["workspace_role"]
          token?: string
          workspace_id: string
        }
        Update: {
          created_at?: string
          email?: string | null
          expires_at?: string
          id?: string
          invited_by?: string
          is_accepted?: boolean
          role?: Database["public"]["Enums"]["workspace_role"]
          token?: string
          workspace_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "workspace_invites_workspace_id_fkey"
            columns: ["workspace_id"]
            isOneToOne: false
            referencedRelation: "workspaces"
            referencedColumns: ["id"]
          },
        ]
      }
      workspace_members: {
        Row: {
          created_at: string
          role: Database["public"]["Enums"]["workspace_role"]
          user_id: string
          workspace_id: string
        }
        Insert: {
          created_at?: string
          role: Database["public"]["Enums"]["workspace_role"]
          user_id: string
          workspace_id: string
        }
        Update: {
          created_at?: string
          role?: Database["public"]["Enums"]["workspace_role"]
          user_id?: string
          workspace_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "workspace_members_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "workspace_members_workspace_id_fkey"
            columns: ["workspace_id"]
            isOneToOne: false
            referencedRelation: "workspaces"
            referencedColumns: ["id"]
          },
        ]
      }
      workspaces: {
        Row: {
          active_niche: string | null
          branding: Json
          created_at: string
          id: string
          name: string
          owner_id: string
          platform_keys_enabled: boolean
          slug: string
          type: Database["public"]["Enums"]["workspace_type"]
          updated_at: string
        }
        Insert: {
          active_niche?: string | null
          branding?: Json
          created_at?: string
          id?: string
          name: string
          owner_id: string
          platform_keys_enabled?: boolean
          slug: string
          type: Database["public"]["Enums"]["workspace_type"]
          updated_at?: string
        }
        Update: {
          active_niche?: string | null
          branding?: Json
          created_at?: string
          id?: string
          name?: string
          owner_id?: string
          platform_keys_enabled?: boolean
          slug?: string
          type?: Database["public"]["Enums"]["workspace_type"]
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "workspaces_owner_id_fkey"
            columns: ["owner_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      create_workspace_with_owner: {
        Args: {
          _name: string
          _slug: string
          _type: Database["public"]["Enums"]["workspace_type"]
        }
        Returns: string
      }
      generate_referral_code: { Args: never; Returns: string }
      is_workspace_editor_or_above: {
        Args: { _workspace_id: string }
        Returns: boolean
      }
      is_workspace_member: {
        Args: {
          _role?: Database["public"]["Enums"]["workspace_role"]
          _workspace_id: string
        }
        Returns: boolean
      }
    }
    Enums: {
      billing_plan: "free" | "solo" | "team" | "agency"
      content_kind: "video" | "text" | "youtube" | "url" | "rss"
      content_status: "uploading" | "processing" | "ready" | "failed"
      feedback_type: "bug" | "feature" | "feedback"
      highlight_status: "draft" | "rendering" | "ready" | "failed"
      output_platform:
        | "tiktok"
        | "instagram_reels"
        | "youtube_shorts"
        | "linkedin"
        | "pinterest"
      output_state: "draft" | "review" | "approved" | "exported"
      referral_status: "pending" | "confirmed" | "blocked"
      render_kind:
        | "burn_captions"
        | "assemble_broll"
        | "branded_video"
        | "clip"
        | "batch_clip"
        | "reframe"
        | "subtitles"
        | "avatar"
        | "dub"
        | "faceless"
      render_priority: "normal" | "high"
      render_provider: "shotstack" | "replicate"
      render_status: "rendering" | "done" | "failed"
      scraper_feature:
        | "trending_sounds"
        | "hashtag_query"
        | "competitor_analysis"
        | "viral_discovery"
        | "comment_mining"
      subscription_status:
        | "trialing"
        | "active"
        | "past_due"
        | "canceled"
        | "unpaid"
        | "incomplete"
        | "incomplete_expired"
        | "paused"
      workspace_role: "owner" | "editor" | "viewer" | "client"
      workspace_type: "personal" | "team" | "client"
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
  storage: {
    Tables: {
      buckets: {
        Row: {
          allowed_mime_types: string[] | null
          avif_autodetection: boolean | null
          created_at: string | null
          file_size_limit: number | null
          id: string
          name: string
          owner: string | null
          owner_id: string | null
          public: boolean | null
          type: Database["storage"]["Enums"]["buckettype"]
          updated_at: string | null
        }
        Insert: {
          allowed_mime_types?: string[] | null
          avif_autodetection?: boolean | null
          created_at?: string | null
          file_size_limit?: number | null
          id: string
          name: string
          owner?: string | null
          owner_id?: string | null
          public?: boolean | null
          type?: Database["storage"]["Enums"]["buckettype"]
          updated_at?: string | null
        }
        Update: {
          allowed_mime_types?: string[] | null
          avif_autodetection?: boolean | null
          created_at?: string | null
          file_size_limit?: number | null
          id?: string
          name?: string
          owner?: string | null
          owner_id?: string | null
          public?: boolean | null
          type?: Database["storage"]["Enums"]["buckettype"]
          updated_at?: string | null
        }
        Relationships: []
      }
      buckets_analytics: {
        Row: {
          created_at: string
          deleted_at: string | null
          format: string
          id: string
          name: string
          type: Database["storage"]["Enums"]["buckettype"]
          updated_at: string
        }
        Insert: {
          created_at?: string
          deleted_at?: string | null
          format?: string
          id?: string
          name: string
          type?: Database["storage"]["Enums"]["buckettype"]
          updated_at?: string
        }
        Update: {
          created_at?: string
          deleted_at?: string | null
          format?: string
          id?: string
          name?: string
          type?: Database["storage"]["Enums"]["buckettype"]
          updated_at?: string
        }
        Relationships: []
      }
      buckets_vectors: {
        Row: {
          created_at: string
          id: string
          type: Database["storage"]["Enums"]["buckettype"]
          updated_at: string
        }
        Insert: {
          created_at?: string
          id: string
          type?: Database["storage"]["Enums"]["buckettype"]
          updated_at?: string
        }
        Update: {
          created_at?: string
          id?: string
          type?: Database["storage"]["Enums"]["buckettype"]
          updated_at?: string
        }
        Relationships: []
      }
      migrations: {
        Row: {
          executed_at: string | null
          hash: string
          id: number
          name: string
        }
        Insert: {
          executed_at?: string | null
          hash: string
          id: number
          name: string
        }
        Update: {
          executed_at?: string | null
          hash?: string
          id?: number
          name?: string
        }
        Relationships: []
      }
      objects: {
        Row: {
          bucket_id: string | null
          created_at: string | null
          id: string
          last_accessed_at: string | null
          metadata: Json | null
          name: string | null
          owner: string | null
          owner_id: string | null
          path_tokens: string[] | null
          updated_at: string | null
          user_metadata: Json | null
          version: string | null
        }
        Insert: {
          bucket_id?: string | null
          created_at?: string | null
          id?: string
          last_accessed_at?: string | null
          metadata?: Json | null
          name?: string | null
          owner?: string | null
          owner_id?: string | null
          path_tokens?: string[] | null
          updated_at?: string | null
          user_metadata?: Json | null
          version?: string | null
        }
        Update: {
          bucket_id?: string | null
          created_at?: string | null
          id?: string
          last_accessed_at?: string | null
          metadata?: Json | null
          name?: string | null
          owner?: string | null
          owner_id?: string | null
          path_tokens?: string[] | null
          updated_at?: string | null
          user_metadata?: Json | null
          version?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "objects_bucketId_fkey"
            columns: ["bucket_id"]
            isOneToOne: false
            referencedRelation: "buckets"
            referencedColumns: ["id"]
          },
        ]
      }
      s3_multipart_uploads: {
        Row: {
          bucket_id: string
          created_at: string
          id: string
          in_progress_size: number
          key: string
          metadata: Json | null
          owner_id: string | null
          upload_signature: string
          user_metadata: Json | null
          version: string
        }
        Insert: {
          bucket_id: string
          created_at?: string
          id: string
          in_progress_size?: number
          key: string
          metadata?: Json | null
          owner_id?: string | null
          upload_signature: string
          user_metadata?: Json | null
          version: string
        }
        Update: {
          bucket_id?: string
          created_at?: string
          id?: string
          in_progress_size?: number
          key?: string
          metadata?: Json | null
          owner_id?: string | null
          upload_signature?: string
          user_metadata?: Json | null
          version?: string
        }
        Relationships: [
          {
            foreignKeyName: "s3_multipart_uploads_bucket_id_fkey"
            columns: ["bucket_id"]
            isOneToOne: false
            referencedRelation: "buckets"
            referencedColumns: ["id"]
          },
        ]
      }
      s3_multipart_uploads_parts: {
        Row: {
          bucket_id: string
          created_at: string
          etag: string
          id: string
          key: string
          owner_id: string | null
          part_number: number
          size: number
          upload_id: string
          version: string
        }
        Insert: {
          bucket_id: string
          created_at?: string
          etag: string
          id?: string
          key: string
          owner_id?: string | null
          part_number: number
          size?: number
          upload_id: string
          version: string
        }
        Update: {
          bucket_id?: string
          created_at?: string
          etag?: string
          id?: string
          key?: string
          owner_id?: string | null
          part_number?: number
          size?: number
          upload_id?: string
          version?: string
        }
        Relationships: [
          {
            foreignKeyName: "s3_multipart_uploads_parts_bucket_id_fkey"
            columns: ["bucket_id"]
            isOneToOne: false
            referencedRelation: "buckets"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "s3_multipart_uploads_parts_upload_id_fkey"
            columns: ["upload_id"]
            isOneToOne: false
            referencedRelation: "s3_multipart_uploads"
            referencedColumns: ["id"]
          },
        ]
      }
      vector_indexes: {
        Row: {
          bucket_id: string
          created_at: string
          data_type: string
          dimension: number
          distance_metric: string
          id: string
          metadata_configuration: Json | null
          name: string
          updated_at: string
        }
        Insert: {
          bucket_id: string
          created_at?: string
          data_type: string
          dimension: number
          distance_metric: string
          id?: string
          metadata_configuration?: Json | null
          name: string
          updated_at?: string
        }
        Update: {
          bucket_id?: string
          created_at?: string
          data_type?: string
          dimension?: number
          distance_metric?: string
          id?: string
          metadata_configuration?: Json | null
          name?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "vector_indexes_bucket_id_fkey"
            columns: ["bucket_id"]
            isOneToOne: false
            referencedRelation: "buckets_vectors"
            referencedColumns: ["id"]
          },
        ]
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      allow_any_operation: {
        Args: { expected_operations: string[] }
        Returns: boolean
      }
      allow_only_operation: {
        Args: { expected_operation: string }
        Returns: boolean
      }
      can_insert_object: {
        Args: { bucketid: string; metadata: Json; name: string; owner: string }
        Returns: undefined
      }
      extension: { Args: { name: string }; Returns: string }
      filename: { Args: { name: string }; Returns: string }
      foldername: { Args: { name: string }; Returns: string[] }
      get_common_prefix: {
        Args: { p_delimiter: string; p_key: string; p_prefix: string }
        Returns: string
      }
      get_size_by_bucket: {
        Args: never
        Returns: {
          bucket_id: string
          size: number
        }[]
      }
      list_multipart_uploads_with_delimiter: {
        Args: {
          bucket_id: string
          delimiter_param: string
          max_keys?: number
          next_key_token?: string
          next_upload_token?: string
          prefix_param: string
        }
        Returns: {
          created_at: string
          id: string
          key: string
        }[]
      }
      list_objects_with_delimiter: {
        Args: {
          _bucket_id: string
          delimiter_param: string
          max_keys?: number
          next_token?: string
          prefix_param: string
          sort_order?: string
          start_after?: string
        }
        Returns: {
          created_at: string
          id: string
          last_accessed_at: string
          metadata: Json
          name: string
          updated_at: string
        }[]
      }
      operation: { Args: never; Returns: string }
      search: {
        Args: {
          bucketname: string
          levels?: number
          limits?: number
          offsets?: number
          prefix: string
          search?: string
          sortcolumn?: string
          sortorder?: string
        }
        Returns: {
          created_at: string
          id: string
          last_accessed_at: string
          metadata: Json
          name: string
          updated_at: string
        }[]
      }
      search_by_timestamp: {
        Args: {
          p_bucket_id: string
          p_level: number
          p_limit: number
          p_prefix: string
          p_sort_column: string
          p_sort_column_after: string
          p_sort_order: string
          p_start_after: string
        }
        Returns: {
          created_at: string
          id: string
          key: string
          last_accessed_at: string
          metadata: Json
          name: string
          updated_at: string
        }[]
      }
      search_v2: {
        Args: {
          bucket_name: string
          levels?: number
          limits?: number
          prefix: string
          sort_column?: string
          sort_column_after?: string
          sort_order?: string
          start_after?: string
        }
        Returns: {
          created_at: string
          id: string
          key: string
          last_accessed_at: string
          metadata: Json
          name: string
          updated_at: string
        }[]
      }
    }
    Enums: {
      buckettype: "STANDARD" | "ANALYTICS" | "VECTOR"
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  graphql_public: {
    Enums: {},
  },
  public: {
    Enums: {
      billing_plan: ["free", "solo", "team", "agency"],
      content_kind: ["video", "text", "youtube", "url", "rss"],
      content_status: ["uploading", "processing", "ready", "failed"],
      feedback_type: ["bug", "feature", "feedback"],
      highlight_status: ["draft", "rendering", "ready", "failed"],
      output_platform: [
        "tiktok",
        "instagram_reels",
        "youtube_shorts",
        "linkedin",
        "pinterest",
      ],
      output_state: ["draft", "review", "approved", "exported"],
      referral_status: ["pending", "confirmed", "blocked"],
      render_kind: [
        "burn_captions",
        "assemble_broll",
        "branded_video",
        "clip",
        "batch_clip",
        "reframe",
        "subtitles",
        "avatar",
        "dub",
        "faceless",
      ],
      render_priority: ["normal", "high"],
      render_provider: ["shotstack", "replicate"],
      render_status: ["rendering", "done", "failed"],
      scraper_feature: [
        "trending_sounds",
        "hashtag_query",
        "competitor_analysis",
        "viral_discovery",
        "comment_mining",
      ],
      subscription_status: [
        "trialing",
        "active",
        "past_due",
        "canceled",
        "unpaid",
        "incomplete",
        "incomplete_expired",
        "paused",
      ],
      workspace_role: ["owner", "editor", "viewer", "client"],
      workspace_type: ["personal", "team", "client"],
    },
  },
  storage: {
    Enums: {
      buckettype: ["STANDARD", "ANALYTICS", "VECTOR"],
    },
  },
} as const
